on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bishalcontainer1acr.azurecr.io
        username: ${{ secrets.acr_bishalcontainer1acr_username }}
        password: ${{ secrets.acr_bishalcontainer1acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t bishalcontainer1acr.azurecr.io/test:1
        docker push bishalcontainer1acr.azurecr.io/test:1
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_tdedah_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep tdedah4aeb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace tdedah4aeb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: tdedah4aeb
        container-registry-url: bishalcontainer1acr.azurecr.io
        container-registry-username: ${{ secrets.acr_bishalcontainer1acr_username }}
        container-registry-password: ${{ secrets.acr_bishalcontainer1acr_password }}
        secret-name: tdedahdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: aks-helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:bishalcontainer1acr.azurecr.io/test
          image.tag:1
          imagePullSecrets:
            -name:tdedahdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1
      with:
        namespace: tdedah4aeb
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          bishalcontainer1acr.azurecr.io/test:1
        imagepullsecrets: |
          tdedahdockerauth